spring:
  application:
    name: Calorie Counter
  data:
    mongodb:
      uri: mongodb+srv://cal:cal@vik.ftcozq9.mongodb.net/cal?retryWrites=true&w=majority&appName=vik
  security:
    user:
      name: admin
      password: 1729
cache:
  caffeine:
    maximum-size: 100
    expire-after-write: 10
    expire-after-write-unit: MINUTES
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    root: INFO
